#!/bin/sh

SSL_ARGS="--cert /tmp/certificate --key /tmp/privateKey  --cafile /tmp/certificate"

case "$1" in
  pub)
    shift
    echo "running mosquitto_pub $SSL_ARGS $@"
    mosquitto_pub $SSL_ARGS $@
    ;;
  sub)
    shift
    echo "running mosquitto_sub $SSL_ARGS $@"
    mosquitto_sub $SSL_ARGS $@
    ;;
  *)
    echo "usage: pub|sub"
esac
